baseurl: /
languageCode: en-us
title: "W. Joel Schneider"
theme: basic
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: About Me
      url: /about/
    - name: GitHub
      url: https://github.com/wjschne
    - name: Twitter
      url: https://twitter.com/WJoelSchneider
params:
  author: W. Joel Schneider
  gh_url: https://api.github.com/users
  gh_user: wjschne
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: W. Joel Schneider's Academic Website
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Headshot
    height: 60
    url: headshot.png
    width: 60
