baseurl: "https://wjschne.github.io/"
canonifyurls: true
languageCode: en-us
title: "W. Joel Schneider"
theme: basic
googleAnalytics: ''
disqusShortname: ''
sectionPagesMenu: main
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Home
      url: /
      pre: <i class='fa fa-home'></i>
      weight: 1
    - name: Vita
      url: /Vita
      weight: 8
    - name: Presentations
      url: /presentations
      weight: 3
    - name: Contact Me
      url: /contact
      pre: <i class="fas fa-id-card"></i>
params:
  author: W. Joel Schneider
  gh_url: https://api.github.com/users
  gh_user: wjschne
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: W. Joel Schneider's Academic Website
  favicon: headshot.png
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Headshot
    height: 60
    url: headshot.png
    width: 60
taxonomies:
  category: categories
  tag: tags
  myproject: myprojects


markup:
  goldmark:
    renderer:
      unsafe: true
